### ISSUE TITLE
`wg`: not found

### ISSUE THREAD

**Issue by ndom91** [subspacecommunity/subspace#72] opened 2020-05-24 09:06 UTC
The `wg` binary cannot be found inside the docker container. Although the volume mount is specified in my docker run command. I also tried it via the example docker-compose variant, no luck.

I double checked locally, wg is installed at `/usr/bin/wg` and its not a symlink somewhere. 

I'm at my whits end why in the `entrypoint.sh:139`, while running, it can't find the wg binary.

Any idea whats going on here?

- Ubuntu 18.04 Server x64
- Docker 19.03.8

**Comment by bobbyiliev** [comment] 2020-05-24 09:55
Yes indeed, I noticed the same problem just now, even though I specified the ` --volume /usr/bin/wg:/usr/bin/wg` and also verified that wg is installed on the host.

**Comment by gavinelder** [comment] 2020-05-24 12:52
LMTAL I think this may be a pathing issue on Alpine.

**Comment by gavinelder** [comment] 2020-05-24 18:02
Got to the bottom of it will have a PR later tonight just want to run some e2e tests and clean up.

**Comment by ndom91** [comment] 2020-05-24 18:03
Woohoo! Excited to try this out. Thanks

**Comment by guss77** [comment] 2020-05-24 20:06
I have the same issue, running on Ubuntu 20.04.

@gavinelder probably already solved this, but I want to provide more info - it looks like the problem is that the `wg` binary is linked against a different libc than what is in the alpine-based container of Subspace (or just at a different path). When you mount it into the container, the Linux linker can't find the libc binary - which is what the `not found` error is about.

My workaround was to also mount the host's libc into where the host `wg` expects to find it, by adding the following options to the docker command line:

```
    --volume /lib/x86_64-linux-gnu/libc.so.6:/lib/x86_64-linux-gnu/libc.so.6:ro \
    --volume /lib64/ld-linux-x86-64.so.2:/lib64/ld-linux-x86-64.so.2:ro \
```

**Comment by ndom91** [comment] 2020-05-24 20:57
@guss77 that quick fix seemed to work for me as well though. Thanks. 

Now its complaining about `Line Unrecognized: 'PrivateKey='` after running `/usr/bin/wg setconf wg0 /data/wireguard/server.conf` haha

**Comment by gavinelder** [comment] 2020-05-24 23:25
I want to take this time to say sorry my testing of the move of docker OS was not sufficient and was based upon some existing host OS setups implicit dependacies Vs explicit. I am working on pushing a fix for this sadly I didn't manage to get to it tonight due to family catch ups and I will get to pushing the changes tomorrow.

**Comment by ndom91** [comment] 2020-05-25 00:00
No worriers @gavinelder, thats what we're here for - to work out the kinks. If we expected everything to function flawlessly I wouldn't be trying a community project on github ;)

**Comment by ishanjain28** [comment] 2020-05-25 17:54
Please consider tagging releases before pushing them to docker hub. :(

**Comment by sourceful-sharon** [comment] 2020-05-26 09:29
@gavinelder will the fix include:
"Line unrecognized: `PrivateKey='
Configuration parsing error
Unable to find /sbin/ip6tables not configuring IPv6 DNS leak Protection"
Which I think @ndom91 was having too yesterday?

**Comment by gavinelder** [comment] 2020-05-26 10:38
@sourceful-sharon Yes it will, the `"Line unrecognized: `PrivateKey='` is due to the private key not being generated correctly and being an empty file so the removal of `/data/*` is required to start up for the first time on the fixed image. 

If you have previously ran subpage this step would not be required.

**Comment by jedieaston** [comment] 2020-05-27 12:25
@gavinelder my /data folder is empty. Building the new docker container (from the pull request) and running is exiting with the same PrivateKey error. Any ideas?

**Comment by gavinelder** [comment] 2020-05-27 12:31
@jedieaston 

I have been doing the following. 

```sh
git clone https://github.com/subspacecommunity/subspace.git
cd subspace 
git checkout un-break
rm -rf /data/*
sudo docker build . -t subspace:test
sudo docker stop subspace
sudo docker rm subspace
sudo docker create docker create \
    --name subspace \
    --restart always \
    --network host \
    --cap-add NET_ADMIN \
    --volume /data:/data \
    --env SUBSPACE_HTTP_HOST="subspace.example.com" \
    --env SUBSPACE_NAMESERVER="1.1.1.1" \
    --env SUBSPACE_LISTENPORT="51820" \
    --env SUBSPACE_IPV4_POOL="10.99.97.0/24" \
    --env SUBSPACE_IPV4_GW="10.99.97.1" \
    subspace:test
sudo docker start subspace
sudo docker logs subspace
```

**Comment by jedieaston** [comment] 2020-05-27 13:09
@gavinelder Using those instructions, the container is exiting with:

` run-parts: /etc/run_once: No such file or directory `

(Building on Ubuntu 20.04 LTS + Docker 19.03.9. Tried it on 16.04 to a similar result)

**Comment by gavinelder** [comment] 2020-05-27 13:23
@jedieaston pushed another commit, those dir's are not needed so removed.

**Comment by jedieaston** [comment] 2020-05-27 13:40
Awesome, it works!

The only thing I'm still noticing is that if you use the docker-compose example, with /data mapped to /data (instead of /opt/docker/subspace:/data), it still fails with the PrivateKey error. However, if you run the docker container outside of a compose file, and then run the compose file, the services start back up fine (since the conf files were already created).

Otherwise, seems to work fine! Thanks.

**Comment by bobbyiliev** [comment] 2020-05-27 14:41
Thanks a lot @gavinelder it works for me as well! Well done and thanks for the quick fixes!

Just need to get the latest image available on Docker Hub as well.

**Comment by gavinelder** [comment] 2020-05-27 16:42
@bobbyiliev need to have the PR reviewed first currently blocked on that.

**Comment by bruse** [comment] 2020-05-29 08:12
#75 Related PR for those interested

**Comment by gavinelder** [comment] 2020-06-09 10:12
Hi this PR has now landed 

Going to keep this issue open for another couple of days for any uses,

**Closed** 2020-06-13 12:26 UTC
Labels: bug
